.PHONY: all letter clean

all: letter clean

letter:
	pdflatex letter.tex
	pdflatex letter.tex
	pdflatex letter.tex

clean:
	rm -f *.aux
	rm -f *.lof
	rm -f *.log
	rm -f *.lol
	rm -f *.lot
	rm -f *.out
	rm -f *.toc
